version: "3.8"

services:
  app:
    image: manifest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    volumes:
      - ./manifest/backend.db:/app/manifest/backend.db
      - ./public:/app/public
